---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: demarauder/portfolio:latest
        # This app listens on port 80 for web traffic by default.
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
---
